### ISSUE TITLE
Création / Progression - Magicien niveau 15+ n'on pas de copie de sort

### ISSUE THREAD

**Issue by ghost** [Dominik-Giroux/Mythall-3.5#22]

**Comment by PhilGravel** [comment]
Pour ajouter plus d'infos :

La liste de sort permis à recopier est vide si le mage passe de niveau 15 à 16 en montant. 

@Dominik-Giroux  As-tu testé sur un perso qui n'avait pas d'intel? J'ai pas le code devant moi, mais c'est possiblement parce qu'il croit avoir accès à des sorts lvl 10

# Personnage de test
![image](https://user-images.githubusercontent.com/48894940/169444794-58c7b73b-5270-40f1-9685-0f5b6954d9e1.png)

# Affichage de progression
![image](https://user-images.githubusercontent.com/48894940/169444783-e675ddae-6c25-4a78-9f1c-56fadcf23794.png)
